package br.com.fatec.mogi.inventory_service.common.domain.enums;

public enum FuncionalidadesEnum {

	CADASTRO_USUARIO_RELACIONADO, REDEFINIR_SENHA, CADASTRO_CATEGORIA, DELETAR_CATEGORIA, LISTAR_CATEGORIA,
	CADASTRO_LOCALIZACAO, DELETAR_LOCALIZACAO, LISTAR_LOCALIZCAO, CADASTRO_ITEM, EDITAR_ITEM, ALTERAR_STATUS_ITEM,
	DELETAR_ITEM, LISTAR_ITEM, GERAR_RELATORIO_ITEM, INICIAR_AUDITORIA, GERAR_RELATORIO_AUDITORIA,
	CONFIRMAR_LOCALIZACAO, FINALIZAR_AUDITORIA;

}
