DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS funcionalidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionalidade VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS funcao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    CONSTRAINT uk_funcao_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS funcao_funcionalidade (
    funcao_id BIGINT NOT NULL,
    funcionalidade_id BIGINT NOT NULL,
    PRIMARY KEY (funcao_id, funcionalidade_id),
    CONSTRAINT fk_funcao_funcionalidade_funcao FOREIGN KEY (funcao_id) REFERENCES funcao (id) ON DELETE CASCADE,
    CONSTRAINT fk_funcao_funcionalidade_funcionalidade FOREIGN KEY (funcionalidade_id) REFERENCES funcionalidade (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    ativo BOOLEAN,
    data_criacao TIMESTAMP,
    data_alteracao TIMESTAMP,
    administrador_id BIGINT,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    FOREIGN KEY (administrador_id) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS usuario_funcao (
    usuario_id BIGINT NOT NULL,
    funcao_id BIGINT NOT NULL,
    PRIMARY KEY (usuario_id, funcao_id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE,
    FOREIGN KEY (funcao_id) REFERENCES funcao(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categoria_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS localizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    andar VARCHAR(100) NOT NULL,
    nome_sala VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS status_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_entrada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_item VARCHAR(200) NOT NULL,
    descricao_curta VARCHAR(255),
    descricao_detalhada CLOB,
    numero_serie VARCHAR(100),
    codigo_item VARCHAR(100),
    CONSTRAINT uk_item_codigo UNIQUE (codigo_item),
    data_cadastro TIMESTAMP,
    data_alteracao TIMESTAMP,
    categoria_item_id BIGINT,
    localizacao_id BIGINT,
    status_item_id BIGINT,
    tipo_entrada_id BIGINT,
    nota_fiscal VARCHAR(255),
    CONSTRAINT fk_item_categoria FOREIGN KEY (categoria_item_id) REFERENCES categoria_item(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_localizacao FOREIGN KEY (localizacao_id) REFERENCES localizacao(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_status FOREIGN KEY (status_item_id) REFERENCES status_item(id) ON DELETE SET NULL,
    CONSTRAINT fk_item_tipo_entrada FOREIGN KEY (tipo_entrada_id) REFERENCES tipo_entrada(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_usuario_email ON usuario(email);
CREATE INDEX IF NOT EXISTS idx_funcao_nome ON funcao(nome);
CREATE INDEX IF NOT EXISTS idx_funcionalidade_nome ON funcionalidade(funcionalidade);
