name: CD FatecInventory

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'semeru'
          java-version: '21'

      - name: Build Maven
        run: mvn clean package -DskipTests

      - name: Upload do JAR
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "target/*.jar"
          target: "inventory-service-jar"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p inventory-service-jar
            pkill -f "java -jar" || true
            nohup java -jar inventory-service-jar/target/*.jar > inventory-service-jar/inventory.log 2>&1 &
